// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // DIRECT_URL, not DATABASE_URL. The CLI needs a session-mode connection:
  // `migrate deploy` holds a Postgres advisory lock across statements, which
  // a transaction-mode pooler can break by swapping the backing session
  // mid-migration. Prisma 7 removed `directUrl`, so the split lives here.
  datasource: {
    url: process.env["DIRECT_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
